name: QLQuickCSV
options:
  bundleIdPrefix: com.qlcsv
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

targets:
  QLQuickCSV:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: QLQuickCSV
        excludes:
          - "*.entitlements"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.qlcsv.QLQuickCSV
        INFOPLIST_FILE: QLQuickCSV/Info.plist
        CODE_SIGN_ENTITLEMENTS: QLQuickCSV/QLQuickCSV.entitlements
        GENERATE_INFOPLIST_FILE: false
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: CSVQLExtension
        embed: true
        codeSign: true
        buildPhase:
          copyFiles:
            destination: pluginsAndFoundation

  CSVQLExtension:
    type: app-extension
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: CSVQLExtension
        excludes:
          - "*.entitlements"
          - "Resources/**"
      - path: CSVQLExtension/Resources
        buildPhase: resources
      - path: Shared
    resources:
      - path: CSVQLExtension/Base.lproj
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.qlcsv.QLQuickCSV.CSVQLExtension
        INFOPLIST_FILE: CSVQLExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: CSVQLExtension/CSVQLExtension.entitlements
        GENERATE_INFOPLIST_FILE: false
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ENABLE_HARDENED_RUNTIME: YES
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
          - "@executable_path/../../../../Frameworks"
    dependencies: []
